name: CI - Actions Tests

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do código
    - name: Checkout
      uses: actions/checkout@v3

    # 2. Instalar .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "9.0.x"

    # 3. Restaurar dependências
    - name: Restore dependencies
      run: dotnet restore

    # 4. Build da solução
    - name: Build
      run: dotnet build --no-restore --configuration Release

    # 5. Executar testes
    - name: Test
      run: dotnet test --no-build --verbosity normal